name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'  # Trigger on any tag creation

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/whatsappbot:${{ env.TAG }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/whatsappbot:${{ env.TAG }}

      - name: Verify Image on Registry
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/whatsappbot:${{ env.TAG }}
